# Generated by Django 4.2.13 on 2026-05-21 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='Nomi')),
                ('center_lat', models.FloatField(verbose_name='Kenglik')),
                ('center_lng', models.FloatField(verbose_name='Uzunlik')),
                ('area_ha', models.FloatField(blank=True, null=True, verbose_name='Maydon (ha)')),
                ('coordinates', models.JSONField(verbose_name='Koordinatalar')),
                ('ndvi_current', models.FloatField(verbose_name='Joriy NDVI')),
                ('ndvi_change', models.FloatField(verbose_name="NDVI o'zgarishi")),
                ('ndvi_monthly', models.JSONField(verbose_name='Oylik NDVI')),
                ('drought_index', models.FloatField(default=0, verbose_name="Qurg'oqchilik indeksi")),
                ('soil_data', models.JSONField(default=dict, verbose_name="Tuproq ma'lumoti")),
                ('weather_data', models.JSONField(default=dict, verbose_name='Ob-havo tarixi')),
                ('ai_analysis', models.JSONField(default=dict, verbose_name='AI tahlili')),
            ],
            options={
                'verbose_name': 'Tahlil natijasi',
                'verbose_name_plural': 'Tahlil natijalari',
                'ordering': ['-created_at'],
            },
        ),
    ]
