# Generated by Django 4.2.13 on 2026-05-21 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('satellite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisresult',
            name='ndwi_current',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Joriy NDWI'),
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='soil_properties',
            field=models.JSONField(default=dict, verbose_name='Tuproq kimyosi (SoilGrids)'),
        ),
    ]
