# Generated by Django 4.2.13 on 2026-05-21 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('satellite', '0002_analysisresult_ndwi_current_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='Dala nomi')),
                ('crop', models.CharField(blank=True, default='', max_length=100, verbose_name='Ekin turi')),
                ('coordinates', models.JSONField(verbose_name='Polygon koordinatalari')),
                ('center_lat', models.FloatField(verbose_name='Markaz kenglik')),
                ('center_lng', models.FloatField(verbose_name='Markaz uzunlik')),
                ('area_ha', models.FloatField(blank=True, null=True, verbose_name='Maydon (ha)')),
                ('last_irrigation', models.DateField(blank=True, null=True, verbose_name="So'nggi sug'orish")),
                ('water_cycle', models.PositiveSmallIntegerField(default=7, verbose_name="Sug'orish davri (kun)")),
                ('notes', models.TextField(blank=True, verbose_name='Izoh')),
            ],
            options={
                'verbose_name': 'Dala',
                'verbose_name_plural': 'Dalalar',
                'ordering': ['-created_at'],
            },
        ),
    ]
