# Generated by Django 4.2.13 on 2026-05-21 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('satellite', '0003_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisresult',
            name='field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analyses', to='satellite.field', verbose_name='Dala'),
        ),
    ]
