# Generated by Django 4.2.13 on 2026-05-22 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('satellite', '0005_analysisresult_user_field_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='field',
            name='last_irrigation',
        ),
        migrations.RemoveField(
            model_name='field',
            name='water_cycle',
        ),
    ]
