# Generated by Django 4.2.13 on 2026-05-22 08:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('satellite', '0006_remove_irrigation_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='CropImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yuklangan vaqti')),
                ('image', models.ImageField(upload_to='crop_images/', verbose_name='Rasm')),
                ('health_status', models.CharField(blank=True, choices=[('healthy', "Sog'lig'i yaxshi"), ('moderate', "O'rtacha"), ('poor', 'Yomon'), ('critical', 'Juda yomon')], max_length=50, verbose_name="Sog'lig'i holati")),
                ('diseases', models.JSONField(default=list, verbose_name='Aniqlab olingan kasalliklar')),
                ('analysis', models.JSONField(default=dict, verbose_name='Batafsil tahlil')),
                ('confidence', models.FloatField(default=0.0, verbose_name='Ishonch darajasi (0-1)')),
                ('field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crop_images', to='satellite.field', verbose_name='Dala')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='crop_images', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Mahsulot rasmi',
                'verbose_name_plural': 'Mahsulot rasmlari',
                'ordering': ['-created_at'],
            },
        ),
    ]
